### ISSUE TITLE
Chained job throws error

### ISSUE THREAD

**Issue by korridor** [christoph-kluge/bref-sqs-laravel#11]
If I chain multiple jobs together then the worker throws the following error:

```
[2021-03-04 16:14:36] staging.ERROR: Call to a member function bound() on null {"exception":"[object] (Error(code: 0): Call to a member function bound() on null at /var/task/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:344)
[stacktrace]
#0 /var/task/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(312): Illuminate\\Queue\\Queue->raiseJobQueuedEvent()
#1 /var/task/vendor/laravel/framework/src/Illuminate/Support/helpers.php(263): Illuminate\\Queue\\Queue->Illuminate\\Queue\\{closure}()
#2 /var/task/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(313): tap()
#3 /var/task/vendor/laravel/framework/src/Illuminate/Queue/SqsQueue.php(99): Illuminate\\Queue\\Queue->enqueueUsing()
#4 /var/task/vendor/christoph-kluge/bref-sqs-laravel/src/Queue/Queue.php(46): Illuminate\\Queue\\SqsQueue->push()
#5 /var/task/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(251): Sikei\\Bref\\Sqs\\Laravel\\Queue\\Queue->push()
#6 /var/task/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(227): Illuminate\\Bus\\Dispatcher->pushCommandToQueue()
#7 /var/task/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(77): Illuminate\\Bus\\Dispatcher->dispatchToQueue()
#8 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php(202): Illuminate\\Bus\\Dispatcher->dispatch()
#9 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(389): Illuminate\\Foundation\\Bus\\PendingDispatch->__destruct()
#10 /var/task/vendor/laravel/framework/src/Illuminate/Bus/Queueable.php(233): dispatch()
#11 /var/task/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(166): App\\Jobs\\SomeJob->dispatchNextJobInChain()
#12 /var/task/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(77): Illuminate\\Queue\\CallQueuedHandler->ensureNextJobInChainIsDispatched()
#13 /var/task/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
#14 /var/task/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(406): Illuminate\\Queue\\Jobs\\Job->fire()
#15 /var/task/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(356): Illuminate\\Queue\\Worker->process()
#16 /var/task/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(307): Illuminate\\Queue\\Worker->runJob()
#17 /var/task/vendor/christoph-kluge/bref-sqs-laravel/src/Commands/SqsWorkCommand.php(77): Illuminate\\Queue\\Worker->runNextJob()
#18 /var/task/vendor/bref/bref/src/Runtime/Invoker.php(34): Sikei\\Bref\\Sqs\\Laravel\\Commands\\SqsWorkCommand->Sikei\\Bref\\Sqs\\Laravel\\Commands\\{closure}()
#19 /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php(102): Bref\\Runtime\\Invoker->invoke()
#20 /var/task/vendor/christoph-kluge/bref-sqs-laravel/src/Commands/SqsWorkCommand.php(81): Bref\\Runtime\\LambdaRuntime->processNextEvent()
#21 /var/task/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Sikei\\Bref\\Sqs\\Laravel\\Commands\\SqsWorkCommand->runWorker()
#22 /var/task/vendor/christoph-kluge/bref-sqs-laravel/src/Commands/SqsWorkCommand.php(57): Illuminate\\Queue\\Console\\WorkCommand->handle()
#23 /var/task/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Sikei\\Bref\\Sqs\\Laravel\\Commands\\SqsWorkCommand->handle()
#24 /var/task/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#25 /var/task/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#26 /var/task/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#27 /var/task/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\\Container\\BoundMethod::call()
#28 /var/task/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#29 /var/task/vendor/symfony/console/Command/Command.php(256): Illuminate\\Console\\Command->execute()
#30 /var/task/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#31 /var/task/vendor/symfony/console/Application.php(971): Illuminate\\Console\\Command->run()
#32 /var/task/vendor/symfony/console/Application.php(290): Symfony\\Component\\Console\\Application->doRunCommand()
#33 /var/task/vendor/symfony/console/Application.php(166): Symfony\\Component\\Console\\Application->doRun()
#34 /var/task/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#35 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#36 /var/task/worker.php(15): Illuminate\\Foundation\\Console\\Kernel->handle()
#37 /var/task/vendor/bref/bref/src/Runtime/FileHandlerLocator.php(43): require('/var/task/worke...')
#38 /opt/bref/bootstrap.php(32): Bref\\Runtime\\FileHandlerLocator->get()
#39 {main}
"} 
```

I am using Laravel 8.29.0 and the current version of this package 1.0.0.
I haven't had time to look at the problem in detail yet, but I thought I could at least share my stack trace.
I replaced the real job class name with `SomeJob`, the rest of the stack trace was not edited.

**Comment by christoph-kluge** [comment]
Could you add an example of the calling code which is dispatching the job?
I may take a look today evening.

**Comment by korridor** [comment]
As you might guess, this is not exactly the real code, but it basically describes what I do.
Hope this helps anyway. In the tests I did were two jobs in the `$jobChain` array.

```php
$jobChain = [];
foreach(...) {
   $ids = new Collection();
   $ids->push('uuid1');
   $ids->push('uuid2');
   array_push($jobChain, new SomeJob($ids));
}

Bus::chain($jobChain)->dispatch();
```

If I understand the error correctly it should also be possible to reproduce this with the following code:

```php
Bus::chain([
  new SomeJob(['test1', 'test2']),
  new SomeJob(['test3', 'test4'])
])->dispatch();
```

```php
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Illuminate\Support\Collection;

class SomeJob implements ShouldQueue
{
    use Dispatchable;
    use InteractsWithQueue;
    use Queueable;
    use SerializesModels;

    /**
     * @var Collection
     */
    public $ids;

    /**
     * The number of seconds the job can run before timing out.
     *
     * @var int
     */
    public $timeout = 900;

    /**
     * The number of times the job may be attempted.
     *
     * @var int
     */
    public $tries = 1;

    /**
     * The number of seconds to wait before retrying the job.
     *
     * @var int
     */
    public $retryAfter = 60;

    /**
     * Create a new job instance.
     *
     * @param Collection $ids
     */
    public function __construct(Collection $ids)
    {
        $this->ids = $ids;
    }

    /**
     * Execute the job.
     *
     * @return void
     * @throws Exception
     */
    public function handle(): void
    {
        foreach ($this->ids as $id) {
            Log::info($id);
        }
    }

}

```

Documentation that I used for this: https://laravel.com/docs/8.x/queues#job-chaining

**Comment by christoph-kluge** [comment]
@korridor I added a fix in #12. It seems that L8 changed it's internals when you use chained jobs.

Anyway I had to set the container. Since we're adding our own connection this was not done by the manager anymore.

Let me know if this fixes your issue 👍

**Comment by korridor** [comment]
@christoph-kluge Thanks for the fast fix. I will test the PR today.

**Comment by korridor** [comment]
@christoph-kluge Just tested it and I still get the same error.
I do not get why this is not working your solution looks good to me.

```
[2021-03-05 13:32:00] staging.ERROR: Call to a member function bound() on null {"exception":"[object] (Error(code: 0): Call to a member function bound() on null at /var/task/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:344)
[stacktrace]
#0 /var/task/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(312): Illuminate\\Queue\\Queue->raiseJobQueuedEvent()
#1 /var/task/vendor/laravel/framework/src/Illuminate/Support/helpers.php(263): Illuminate\\Queue\\Queue->Illuminate\\Queue\\{closure}()
#2 /var/task/vendor/laravel/framework/src/Illuminate/Queue/Queue.php(313): tap()
#3 /var/task/vendor/laravel/framework/src/Illuminate/Queue/SqsQueue.php(99): Illuminate\\Queue\\Queue->enqueueUsing()
#4 /var/task/vendor/christoph-kluge/bref-sqs-laravel/src/Queue/Queue.php(46): Illuminate\\Queue\\SqsQueue->push()
#5 /var/task/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(251): Sikei\\Bref\\Sqs\\Laravel\\Queue\\Queue->push()
#6 /var/task/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(227): Illuminate\\Bus\\Dispatcher->pushCommandToQueue()
#7 /var/task/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(77): Illuminate\\Bus\\Dispatcher->dispatchToQueue()
#8 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Bus/PendingDispatch.php(202): Illuminate\\Bus\\Dispatcher->dispatch()
#9 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(389): Illuminate\\Foundation\\Bus\\PendingDispatch->__destruct()
#10 /var/task/vendor/laravel/framework/src/Illuminate/Bus/Queueable.php(233): dispatch()
#11 /var/task/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(166): App\\Jobs\\SomeJob->dispatchNextJobInChain()
#12 /var/task/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(77): Illuminate\\Queue\\CallQueuedHandler->ensureNextJobInChainIsDispatched()
#13 /var/task/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\\Queue\\CallQueuedHandler->call()
#14 /var/task/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(406): Illuminate\\Queue\\Jobs\\Job->fire()
#15 /var/task/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(356): Illuminate\\Queue\\Worker->process()
#16 /var/task/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(307): Illuminate\\Queue\\Worker->runJob()
#17 /var/task/vendor/christoph-kluge/bref-sqs-laravel/src/Commands/SqsWorkCommand.php(78): Illuminate\\Queue\\Worker->runNextJob()
#18 /var/task/vendor/bref/bref/src/Runtime/Invoker.php(34): Sikei\\Bref\\Sqs\\Laravel\\Commands\\SqsWorkCommand->Sikei\\Bref\\Sqs\\Laravel\\Commands\\{closure}()
#19 /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php(102): Bref\\Runtime\\Invoker->invoke()
#20 /var/task/vendor/christoph-kluge/bref-sqs-laravel/src/Commands/SqsWorkCommand.php(82): Bref\\Runtime\\LambdaRuntime->processNextEvent()
#21 /var/task/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Sikei\\Bref\\Sqs\\Laravel\\Commands\\SqsWorkCommand->runWorker()
#22 /var/task/vendor/christoph-kluge/bref-sqs-laravel/src/Commands/SqsWorkCommand.php(57): Illuminate\\Queue\\Console\\WorkCommand->handle()
#23 /var/task/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Sikei\\Bref\\Sqs\\Laravel\\Commands\\SqsWorkCommand->handle()
#24 /var/task/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#25 /var/task/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#26 /var/task/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#27 /var/task/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\\Container\\BoundMethod::call()
#28 /var/task/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#29 /var/task/vendor/symfony/console/Command/Command.php(256): Illuminate\\Console\\Command->execute()
#30 /var/task/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#31 /var/task/vendor/symfony/console/Application.php(971): Illuminate\\Console\\Command->run()
#32 /var/task/vendor/symfony/console/Application.php(290): Symfony\\Component\\Console\\Application->doRunCommand()
#33 /var/task/vendor/symfony/console/Application.php(166): Symfony\\Component\\Console\\Application->doRun()
#34 /var/task/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\\Component\\Console\\Application->run()
#35 /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#36 /var/task/worker.php(15): Illuminate\\Foundation\\Console\\Kernel->handle()
#37 /var/task/vendor/bref/bref/src/Runtime/FileHandlerLocator.php(43): require('/var/task/worke...')
#38 /opt/bref/bootstrap.php(32): Bref\\Runtime\\FileHandlerLocator->get()
#39 {main}
"} 
```

**Comment by christoph-kluge** [comment]
I think I misread the "connections" and "connectors" property. I need to setup a test-suite localstack or AWS with multiple Larvel versions for myself. This manual-testing is not really usable :/

Anyway let me check again. I will compare the versions and check where the container is missing.

**Comment by christoph-kluge** [comment]
While following the code I see that it appears after the first Job is executed correctly. In that case he's re-queueing the following items in order. This perhaps has a fresh `SqsQueue` instance without the container. Going to investigate further.

**Comment by christoph-kluge** [comment]
@korridor I've pushed a new commit. May I ask you to test it?

After the first Job is done it will push the following job into the queue. In that case it's using the parent `SqsQueue` which does not contain the container. 

My fix is passing/forwading the container (and connection-name) into the underlying implementation.

**Comment by christoph-kluge** [comment]
I would also say that setting `setContainer()` inside `SqsWorkCommand` is not necessary anymore.

**Comment by korridor** [comment]
@christoph-kluge Just tested the new changes and it works. Thanks a lot for the fast response!
