### ISSUE TITLE
Laravel 8 support

### ISSUE THREAD

**Issue by korridor** [christoph-kluge/bref-sqs-laravel#8]
I tried to use this plugin with Laravel 8, but I get the following error:

```
errorMessage | The "name" option does not exist.
-- | --
errorType | Symfony\Component\Console\Exception\InvalidArgumentException
stack.0 | #0   /var/task/vendor/laravel/framework/src/Illuminate/Console/Concerns/InteractsWithIO.php(111):  Symfony\Component\Console\Input\Input->getOption()
stack.1 | #1 /var/task/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(128): Illuminate\Console\Command->option()
stack.2 | #2   /var/task/vendor/christoph-kluge/bref-sqs-laravel/src/Commands/SqsWorkCommand.php(68):  Illuminate\Queue\Console\WorkCommand->gatherWorkerOptions()
stack.3 | #3  /var/task/vendor/bref/bref/src/Runtime/Invoker.php(34):  Sikei\Bref\Sqs\Laravel\Commands\SqsWorkCommand->Sikei\Bref\Sqs\Laravel\Commands\{closure}()
stack.4 | #4 /var/task/vendor/bref/bref/src/Runtime/LambdaRuntime.php(102): Bref\Runtime\Invoker->invoke()
stack.5 | #5   /var/task/vendor/christoph-kluge/bref-sqs-laravel/src/Commands/SqsWorkCommand.php(72):  Bref\Runtime\LambdaRuntime->processNextEvent()
stack.6 | #6   /var/task/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100):  Sikei\Bref\Sqs\Laravel\Commands\SqsWorkCommand->runWorker()
stack.7 | #7   /var/task/vendor/christoph-kluge/bref-sqs-laravel/src/Commands/SqsWorkCommand.php(53):  Illuminate\Queue\Console\WorkCommand->handle()
stack.8 | #8   /var/task/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36):  Sikei\Bref\Sqs\Laravel\Commands\SqsWorkCommand->handle()
stack.9 | #9   /var/task/vendor/laravel/framework/src/Illuminate/Container/Util.php(40):  Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
stack.10 | #10   /var/task/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93):  Illuminate\Container\Util::unwrapIfClosure()
stack.11 | #11   /var/task/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37):  Illuminate\Container\BoundMethod::callBoundMethod()
stack.12 | #12 /var/task/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\Container\BoundMethod::call()
stack.13 | #13 /var/task/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call()
stack.14 | #14 /var/task/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute()
stack.15 | #15   /var/task/vendor/laravel/framework/src/Illuminate/Console/Command.php(121):  Symfony\Component\Console\Command\Command->run()
stack.16 | #16 /var/task/vendor/symfony/console/Application.php(971): Illuminate\Console\Command->run()
stack.17 | #17 /var/task/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand()
stack.18 | #18 /var/task/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun()
stack.19 | #19   /var/task/vendor/laravel/framework/src/Illuminate/Console/Application.php(93):  Symfony\Component\Console\Application->run()
stack.20 | #20   /var/task/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129):  Illuminate\Console\Application->run()
stack.21 | #21 /var/task/worker.php(15): Illuminate\Foundation\Console\Kernel->handle()
stack.22 | #22 /var/task/vendor/bref/bref/src/Runtime/FileHandlerLocator.php(43): require('/var/task/worke...')
stack.23 | #23 /opt/bref/bootstrap.php(32): Bref\Runtime\FileHandlerLocator->get()
stack.24 | #24 {main}
```

I will try to look into this further in the following days, but any tips from your side would help.

**Comment by korridor** [comment]
See #9

**Comment by christoph-kluge** [comment]
@korridor thank you for you support. Changes are added and released as stable v1.
